spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: false
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/vin
    username: myuser
    password: secret
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret
  docker:
    compose:
      enabled: true
      file: ingester/compose.yaml
app:
  rabbitmq:
    exchange: energie-vin
    queue: wines
    routing-key: energie.vin.routing
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: false
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://postgres:5432/vin
    username: myuser
    password: secret
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: secret
app:
  rabbitmq:
    exchange: energie-vin
    queue: wines
    routing-key: energie.vin.routing