spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: false
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/vin
    username: myuser
    password: secret
  docker:
    compose:
      enabled: true
      file: ingester/compose.yaml
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: false
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://postgres:5432/vin
    username: myuser
    password: secret