services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB=vin'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    networks:
      - vin_network_back
      - vin_network_ingester
  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: 'rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
      - '15672'
    networks:
      - vin_network_ingester
  backend:
    build: backend/.
    image: irobire/vin-back:latest
    container_name: 'backend'
    environment:
      - 'PROFILE=prod'
    ports:
      - '8586:8080'
    networks:
      - vin_network_back
  ingester:
    build: ingester/.
    image: irobire/vin-ingester:latest
    container_name: 'ingester'
    environment:
      - 'PROFILE=prod'
    ports:
      - '8686:8080'
    networks:
      - vin_network_ingester
  winescrapper:
    build: winescrapper/.
    image: irobire/vin-winescrapper:latest
    container_name: 'winescrapper'
    environment:
      - 'PROFILE=prod'
    ports:
      - '8786:8080'
    networks:
      - vin_network_ingester
networks:
  vin_network_back:
    driver: bridge
  vin_network_ingester:
    driver: bridge