services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=vin'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    networks:
      - vin_network
networks:
  vin_network:
    driver: bridge