name: Build Docker and Deploy on Prod

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker backend
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: irobire/vin-back
      - name: Build and push Docker image backend
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: irobire/vin-back:latest
      - name: Docker Push backend
        run: docker push irobire/vin-back:latest
      - name: Extract metadata (tags, labels) for Docker ingester
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: irobire/vin-ingester
      - name: Build and push Docker image ingester
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./ingester/Dockerfile
          push: true
          tags: irobire/vin-ingester:latest
      - name: Docker Push ingester
        run: docker push irobire/vin-ingester:latest
      - name: Restart the docker microservice
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker compose --profile prod stop backend ingester
            docker compose --profile prod pull backend ingester
            docker compose --profile prod up --no-start backend ingester
            docker compose --profile prod start backend ingester
